### ISSUE TITLE
pip install neco-net-compiler

### ISSUE THREAD

**Issue by fkgl** [Lvyn/neco-net-compiler#6]
Hi, 
I'm trying to install  neco-net-compiler  with command " pip install neco-net-compiler" but the following error appear
----------------------------------error----------------------------------------------
ERROR: Could not find a version that satisfies the requirement neco-net-compiler (from versions: none)
ERROR: No matching distribution found for neco-net-compiler
---------------------------
than I try with command "python -m pip install git+https://github.com/Lvyn/neco-net-compiler.git" but the following error appear
--------------------------------***error***----------------------------------------
Collecting git+https://github.com/Lvyn/neco-net-compiler
  Cloning https://github.com/Lvyn/neco-net-compiler to c:\users\fk\appdata\local\temp\pip-req-build-moaco03_
  Running command git clone -q https://github.com/Lvyn/neco-net-compiler 'C:\Users\FK\AppData\Local\Temp\pip-req-build-moaco03_'
    ERROR: Command errored out with exit status 1:
     command: 'G:\Python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\FK\\AppData\\Local\\Temp\\pip-req-build-moaco03_\\setup.py'"'"'; __file__='"'"'C:\\Users\\FK\\AppData\\Local\\Temp\\pip-req-build-moaco03_\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\FK\AppData\Local\Temp\pip-pip-egg-info-iyyli5jx'
         cwd: C:\Users\FK\AppData\Local\Temp\pip-req-build-moaco03_\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\FK\AppData\Local\Temp\pip-req-build-moaco03_\setup.py", line 18
        print "usage TODO"
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("usage TODO")?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
-------------------------------------
Please someone help me.

**Comment by Lvyn** [comment]
Hello,
I'm sorry but pip installation is not supported.
Neco development of is on hold on my side. I accept and merge pull requests but that's all.
However, you can still install Neco using setup.py.
Also the Syntax error at the bottom implies that you are using Python3.x but Neco uses Python2.7

Best regards

**Comment by fkgl** [comment]
@Lvyn 
Hello,
That's right i used Python3.x.
Thank you for your reply

Best regards
